Changes for making debug mode optional while creating Power VS client
openshift/cluster-api-provider-powervs pull request #11
Opened 2021-06-30 06:17 UTC by Karthik-K-N

This PR contains the changes for making debug mode optional while creating Power VS client

2021-06-30 06:17 UTC, Karthik-K-N commented
/cc @mkumatag

2021-06-30 07:36 UTC, mkumatag requested changes

2021-06-30 07:36 UTC, mkumatag commented on pkg/client/powervs_client.go
> +}
klog got some of these functions, see if it works?

```golang
        if klog.V(debugLevel).Enabled() {
                fmt.Println("debug level")
        }
```

2021-06-30 07:56 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +}
Yes, It works perfectly fine for our use case, Thanks

2021-06-30 08:30 UTC, mkumatag commented
/retest

2021-06-30 10:44 UTC, Karthik-K-N commented
/test generate

2021-07-01 06:24 UTC, Karthik-K-N commented
/assign @mkumatag

2021-07-01 06:25 UTC, mkumatag commented
@Karthik-K-N can you please squash all 4 commits

2021-07-01 06:38 UTC, mkumatag approved these changes
/lgtm

2021-07-01 06:39 UTC, mkumatag commented
/approve

2021-07-01 06:40 UTC, merged