Add support for ServiceEndpoints
openshift/cluster-api-provider-powervs pull request #31
Opened 2021-10-13 09:09 UTC by Karthik-K-N

2021-10-14 06:03 UTC, mkumatag requested changes
The overall approach seems ok to me, here is what we need to do:

- Test with the IBM Cloud staging env with a simple mapi flow with k8s cluster without OCP installed
- Add unit testcases for the newly added code.

2021-10-14 06:03 UTC, mkumatag commented on pkg/client/powervs_client.go
> +	//EndPointKeyToEnvNameMap contains the endpoint key to corresponding environment variable name 	//TODO: Finalize the custom service key names
we need to discuss the naming part, lets put together the information in one of the GH issue and brainstorm.

2021-10-14 09:31 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +	return buildCustomEndpointsMap(infra.Status.PlatformStatus.AWS.ServiceEndpoints), nil
Is is supposed to be PowerVS and updated accordingly

2021-10-14 09:34 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +		"region": "IBMCLOUD_REGION",
This map contains mapping of key to environmental variable and region being used [here](https://github.com/Karthik-K-N/cluster-api-provider-powervs-1/blob/0e15653fa8fc98a2ec97369c2091d12559b5c84a/pkg/client/powervs_client.go#L168 ), so added here for easier accibility.

2021-10-19 07:48 UTC, mkumatag commented on pkg/client/powervs_client_test.go
> +		"pe":  "test-region.power-iaas.cloud.ibm.com",
I see the API got this check for checking to ensure it starts with `https` here - https://github.com/openshift/api/blob/864d80f741744d2dc831590de8b2fc0b32f8779d/config/v1/types_infrastructure.go#L614, not sure it will allow users to specific without https

2021-10-19 08:29 UTC, Karthik-K-N commented on go.mod
>  	// kube 1.18
Updated in recent commit

2021-10-21 05:15 UTC, Karthik-K-N commented
> > `machine exists: powervs-actuator-testing-machine-gjtmj: failed to create scope for machine: failed to create powervs client: no matches for kind "Infrastructure" in version "config.openshift.io/v1"`
> > Observed the same issue on aws cluster api provider on minikube cluster.
> 
> this is because of the infrastructure crd is missing, try creating this crd and check how it goes: https://github.com/openshift/api/blob/master/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml

After applying the above CRD  , I am no more seeing this error

2021-10-21 05:41 UTC, mkumatag commented
/retest

2021-11-08 12:03 UTC, Karthik-K-N commented
Tested the changes on plane k8 cluster powered by minikube, Following are the results
1. Created a infrastructure object with incorrect iam endpoint and resource controller
```
karthikkn@Karthiks-MacBook-Pro clusterbot % oc get infrastructure/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2021-11-08T10:02:01Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:platformSpec:
          .: {}
          f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-11-08T10:02:01Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:cloudConfig:
          .: {}
          f:name: {}
      f:status:
        .: {}
        f:apiServerInternalURI: {}
        f:apiServerURL: {}
        f:controlPlaneTopology: {}
        f:etcdDiscoveryDomain: {}
        f:infrastructureName: {}
        f:infrastructureTopology: {}
        f:platform: {}
        f:platformStatus:
          .: {}
          f:powervs:
            .: {}
            f:region: {}
            f:serviceEndpoints: {}
            f:zone: {}
          f:type: {}
    manager: ___go_build_awesomeProject1
    operation: Update
    time: "2021-11-08T11:05:16Z"
  name: cluster
  resourceVersion: "50185"
  uid: b2125b1a-6a27-4f7c-a660-98b989a1e9bb
spec:
  platformSpec:
    type: PowerVS
status:
  apiServerInternalURI: ""
  apiServerURL: ""
  controlPlaneTopology: HighlyAvailable
  etcdDiscoveryDomain: ""
  infrastructureName: ""
  infrastructureTopology: HighlyAvailable
  platform: PowerVS
  platformStatus:
    powervs:
      region: ""
      serviceEndpoints:
      - name: iam
        url: https://test.iam.cloud.ibm.com
      - name: rc
        url: https://test.resource-controller.cloud.ibm.com
      zone: ""
    type: PowerVS
```

2. Tested the changes by running the power vs capi
`E1108 16:47:03.673863   12434 controller.go:304] controller-runtime/manager/controller/machine_controller "msg"="Reconciler error" "error"="powervs-actuator-testing-machine-gjtmj: failed to create scope for machine: failed to create powervs client: Post \"https://test.iam.cloud.ibm.com/identity/token\": dial tcp: lookup test.iam.cloud.ibm.com: no such host" "name"="powervs-actuator-testing-machine-gjtmj" "namespace"="openshift-machine-api"`

3. Similarly tested with incorrect power cloud endpoint 

`E1108 16:51:42.571359   12559 nodeupdate_controller.go:109] minikube: failed to GetInstances for ocp-validation-toronto-01, with error: Failed to Get all PVM Instances of Power Instance e8f845fa-8caf-4228-bf1c-83dd62c57666 :Get "https://https:%2F%2Ftest-region.power-iaas.cloud.ibm.com/pcloud/v1/cloud-instances/e8f845fa-8caf-4228-bf1c-83dd62c57666/pvm-instances": dial tcp: lookup https://test-region.power-iaas.cloud.ibm.com: no such host`

2021-11-08 12:22 UTC, mkumatag commented
> Tested the changes on plane k8 cluster powered by minikube, Following are the results
> 
> 1. Created a infrastructure object with incorrect iam endpoint and resource controller

can we test with real values for IBM cloud staging area.?

2021-11-16 08:23 UTC, Karthik-K-N commented
Tested the changes on ibm cloud staging area that is https://test.cloud.ibm.com and able to provision the machine

Status field of infrastructure object:
```
status:
  apiServerInternalURI: https://api-int.rdr-ocp-kar27.scnl-ibm.com:6443
  apiServerURL: https://api.rdr-ocp-kar27.scnl-ibm.com:6443
  controlPlaneTopology: HighlyAvailable
  etcdDiscoveryDomain: ""
  infrastructureName: rdr-ocp-kar27-h4bxx
  infrastructureTopology: HighlyAvailable
  platform: PowerVS
  platformStatus:
    powervs:
      region: lon
      serviceEndpoints:
      - name: iam
        url: https://iam.test.cloud.ibm.com
      - name: rc
        url: https://resource-controller.test.cloud.ibm.com
      - name: pe
        url: https://dal.power-iaas.test.cloud.ibm.com
      zone: lon04
    type: PowerVS
```

Sample machine spec:
```
---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  generateName: powervs-actuator-testing-machine-
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: powervs-actuator-k8s
spec:
  providerSpec:
    value:
![vm_in_cloud](https://user-images.githubusercontent.com/42797478/141947727-1ee1b8af-3222-4a66-a35a-9f125ce1600e.png)

      apiVersion: powervsproviderconfig.openshift.io/v1alpha1
      kind: PowerVSMachineProviderConfig
      serviceInstanceID: f3b59a95-d2c5-46e0-9459-9cea76429c6e
      image:
        name: rhcos-410-84-202111011607-0
      userDataSecret:
        name: worker-user-data
      credentialsSecret:
        name: powervs-credentials
      sysType: s922
      procType: shared
      processors: 0.25
      memory: 8
      network:
        name: ocp-net
      keyPairName: karthik-ssh
```

Machine resource created in ocp cluster:
```
karthikkn@Karthiks-MacBook-Pro cluster-api-provider-powervs-1 % oc get machines -A
NAMESPACE               NAME                                     PHASE         TYPE   REGION   ZONE   AGE
openshift-machine-api   powervs-actuator-testing-machine-zjkmm   Provisioned                          10m
openshift-machine-api   rdr-ocp-kar27-h4bxx-master-0             Running                              3d21h
openshift-machine-api   rdr-ocp-kar27-h4bxx-master-1             Running                              3d21h
openshift-machine-api   rdr-ocp-kar27-h4bxx-master-2             Running                              3d21h
openshift-machine-api   rdr-ocp-kar27-h4bxx-worker-6nkt8         Running                              3d21h
openshift-machine-api   rdr-ocp-kar27-h4bxx-worker-9k5t2         Running                              3d21h
openshift-machine-api   rdr-ocp-kar27-h4bxx-worker-pcbm2         Running                              3d21h
```

The vm got created in ibm test cloud
![vm_in_cloud](https://user-images.githubusercontent.com/42797478/141947779-54d7bc2a-2c81-4828-84ef-067d608d2051.png)

2021-11-16 08:34 UTC, mkumatag commented
>       - name: pe
>         url: https://dal.power-iaas.test.cloud.ibm.com
>       zone: lon04
>     type: PowerVS

Good progress Made.!

2021-11-22 05:13 UTC, mkumatag requested changes

2021-11-22 06:48 UTC, mkumatag requested changes

2021-11-22 06:48 UTC, mkumatag commented on pkg/client/powervs_client.go
> +		if err = setCustomEndpoints(customEndpointsMap, []string{"iam", "rc", "pe"}); err != nil {
I still see a `pe` reference here,! I'm wondering if we come up with this array from the above maps keys or some better way?

2021-11-29 05:52 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +		if err = setCustomEndpoints(customEndpointsMap, []string{"iam", "rc", "pe"}); err != nil {
Created a function named `getCustomEndPointKeys` to extract key from map

2021-11-29 05:52 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +		if customEndpoint.Name == "pe" {
Moved to a constant named `powerIaaSCustomEndpointName`

2021-11-29 05:52 UTC, Karthik-K-N commented on pkg/client/powervs_client.go
> +}
Merged multiple functions into single one in the latest commit

2021-11-29 05:53 UTC, Karthik-K-N commented
All review comments has been addressed and Now the PR is ready for review.

2021-11-30 11:14 UTC, mkumatag approved these changes
/lgtm

2021-11-30 11:15 UTC, mkumatag commented
/approve

2021-11-30 11:18 UTC, merged